version: "3.8"

services:
  registration_service:
    build:
      context: ./registration_service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true