version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
      - "8443:8443"
    restart: unless-stopped
    networks:
      - dokploy-network
    depends_on:
      - frontend
networks:
  dokploy-network:
    external: true