version: "3.8"

services:
  loki:
    user: "root"
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dokploy-network

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./monitoring/logs:/var/log:ro
      - ./monitoring/promtail/promtail-config.prod.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9080/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dokploy-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3334:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  grafana-data:
  loki-data:
