version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - dokploy-network

  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8002:8000"
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      api_gateway:
        condition: service_started
    networks:
      - dokploy-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-admin}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network


networks:
  dokploy-network:
    external: true
