server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          app: educational-platform
          env: prod
          __path__: /var/log/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            module: module
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          module:
