"""add_fields_for_oauth

Revision ID: c54703e51b42
Revises: f58b4d906a74
Create Date: 2025-01-14 07:16:57.911417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54703e51b42'
down_revision: Union[str, None] = 'f58b4d906a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('yandex_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.create_unique_constraint(None, 'users', ['yandex_id'])
    op.create_unique_constraint(None, 'users', ['vk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'yandex_id')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ###
