"""change type of google_id

Revision ID: 2dd53b43130f
Revises: a8c64cc2c293
Create Date: 2025-01-22 21:29:56.508242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dd53b43130f"
down_revision: Union[str, None] = "a8c64cc2c293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "google_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "google_id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
