"""add_test_models_to_dict

Revision ID: 4b22e4d8550a
Revises: 60a1c6b53e1c
Create Date: 2025-02-09 23:01:58.335505

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b22e4d8550a"
down_revision: Union[str, None] = "60a1c6b53e1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # хе-хе-хе
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
