"""add_field_popularity_count_in_tests

Revision ID: 5b8e7a7306b3
Revises: 4b22e4d8550a
Create Date: 2025-02-13 22:36:22.949940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8e7a7306b3'
down_revision: Union[str, None] = '4b22e4d8550a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку с возможностью NULL
    op.add_column('tests', sa.Column('popularity_count', sa.Integer(), nullable=True))

    # 2. Обновляем существующие записи
    op.execute("UPDATE tests SET popularity_count = 0")

    # 3. Меняем колонку на NOT NULL
    op.alter_column('tests', 'popularity_count',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tests', sa.Column('popularity_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'popularity_count')
    # ### end Alembic commands ###
