"""change name avatar and phone is nullable, change type of google_id

Revision ID: a8c64cc2c293
Revises: 46ed165c2d26
Create Date: 2025-01-22 21:26:27.993531

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8c64cc2c293"
down_revision: Union[str, None] = "46ed165c2d26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(), nullable=True))
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("avatar_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
